---
- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: Remove default config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Create www directory
  file: path=/var/www/elk state=directory

- name: Replace default page
  template: src=index.html dest=/var/www/elk/index.html

- name: Adds default config
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
